Remove `brew install python` from Travis OS X conf
This is in response to an error in an [automated continuous integration build](https://travis-ci.org/aaaaalbert/repy_v2/jobs/214290750) that errors out before unit-testing.

After the automatically-run `brew update`, Python 2.7.12 is already installed, and trying to install it once more causes `brew` to fail:

```
brew install python;    ### This is from our .travis.yml CI config and causes the auto update
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core, homebrew/versions).
==> New Formulae
abuse                                    magnetix
advancemame                              mame
advancemenu                              mapcrafter
advancescan                              maven-completion
angband                                  mednafen
angolmois                                mesalib-glw
### ... and many other things
==> Migrating mpfr2 to mpfr@2
==> Unlinking mpfr2
Moving to: /usr/local/Cellar/mpfr@2
==> Linking mpfr@2

Error: python-2.7.12_1 already installed
To install this version, first `brew unlink python`

The command "brew install python;" failed and exited with 1 during .

Your build has been stopped.
```